version: "3"

networks:
  web:

services:
### Nuxt ################################################
  nuxt:
    image: ${CI_REGISTRY_IMAGE}/nuxt:${CI_COMMIT_REF_SLUG}
    build:
      context: ./../
      dockerfile: ./nuxt-dock/nuxt/Dockerfile-prod
    networks:
      - web
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: ".6"
          memory: 300M
      restart_policy:
        condition: on-failure
    ports:
      - "${NUXT_PORT}:3333"
      # Let's also override the exposed port, so we can
      # work in http://localhost:9000
    # volumes:
    #     - ..:/usr/src
  
### Redis ##############################################
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${DATA_PATH_HOST}:/data"
    networks:
      - web

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - web
