FROM node:alpine as builder

RUN apk add --no-cache --virtual .gyp python make g++
WORKDIR /usr/src
COPY . /usr/src
RUN yarn install

FROM node:alpine as app
# Expose env host
# This is needed to ensure communication between containers
# between docker containers
# Already defined in package.json
ENV HOST 0.0.0.0
ENV PORT 3333

WORKDIR /usr/src
COPY . /usr/src
COPY --from=builder /usr/src/node_modules ./node_modules/
RUN ls && yarn build

# Clear the cache
RUN yarn cache clean

#just listing current directory outout
RUN pwd
RUN ls -l

EXPOSE 3000
# Run server app
# CMD yarn $([ -f yarn.lock ] && echo "install") && $(yarn bin)/nuxt dev
CMD [ "yarn", "start" ]
